Task-1

In [1]:
# Unit Converter Program
# Conversion factors
METERS_TO_FEET = 3.28084
KILOGRAMS_TO_POUNDS = 2.20462
LITERS_TO_GALLONS = 0.264172

# Supported categories and their options
CONVERSION_TYPES = {
    "length": ["m to ft", "ft to m"],
    "weight": ["kg to lbs", "lbs to kg"],
    "volume": ["L to gal", "gal to L"]
}

In [2]:
def convert_units(value: float, category: str, direction: str) -> float:
    """
    Convert a value between different units in the specified category.
    
    Parameters:
    -----------
    value : float
        The numerical value to convert
    category : str
        The type of measurement ('length', 'weight', or 'volume')
    direction : str
        The conversion direction (e.g., 'm to ft', 'kg to lbs', etc.)
        
    Returns:
    --------
    float
        The converted value
        
    Raises:
    -------
    ValueError
        If category or direction is not supported
    """
    if category == "length":
        if direction == "m to ft":
            return value * METERS_TO_FEET
        elif direction == "ft to m":
            return value / METERS_TO_FEET
            
    elif category == "weight":
        if direction == "kg to lbs":
            return value * KILOGRAMS_TO_POUNDS
        elif direction == "lbs to kg":
            return value / KILOGRAMS_TO_POUNDS
            
    elif category == "volume":
        if direction == "L to gal":
            return value * LITERS_TO_GALLONS
        elif direction == "gal to L":
            return value / LITERS_TO_GALLONS
            
    raise ValueError(f"Unsupported conversion: {category} - {direction}")

In [3]:
def show_menu_and_get_choice():
    print("\n" + "="*50)
    print("          UNIT CONVERTER")
    print("="*50)
    print("Available categories:\n")
    
    for i, cat in enumerate(CONVERSION_TYPES.keys(), 1):
        print(f"{i}. {cat.capitalize()}")
    
    while True:
        try:
            cat_choice = int(input("\nChoose category (number): "))
            if 1 <= cat_choice <= len(CONVERSION_TYPES):
                category = list(CONVERSION_TYPES.keys())[cat_choice-1]
                break
            else:
                print(f"Please enter a number between 1 and {len(CONVERSION_TYPES)}")
        except ValueError:
            print("Please enter a valid number")
    
    print(f"\nSelected: {category.capitalize()}")
    print("\nAvailable conversions:")
    for i, option in enumerate(CONVERSION_TYPES[category], 1):
        print(f"{i}. {option}")
    
    while True:
        try:
            conv_choice = int(input("\nChoose conversion (number): "))
            if 1 <= conv_choice <= len(CONVERSION_TYPES[category]):
                direction = CONVERSION_TYPES[category][conv_choice-1]
                break
            else:
                print(f"Please enter a number between 1 and {len(CONVERSION_TYPES[category])}")
        except ValueError:
            print("Please enter a valid number")
    
    return category, direction

In [4]:
def main():
    print("Welcome to Unit Converter!")
    
    while True:
        try:
            category, direction = show_menu_and_get_choice()
            
            # Get value to convert
            while True:
                try:
                    value = float(input(f"\nEnter value in {direction.split(' to ')[0]}: "))
                    if value < 0:
                        print("Please enter a non-negative value.")
                        continue
                    break
                except ValueError:
                    print("Please enter a valid number.")
            
            # Perform conversion
            result = convert_units(value, category, direction)
            
            from_unit = direction.split(" to ")[0]
            to_unit   = direction.split(" to ")[1]
            
            print("\n" + "-"*50)
            print(f"{value:.4f} {from_unit} = {result:.4f} {to_unit}")
            print("-"*50)
            
        except ValueError as e:
            print(f"\nError: {e}")
        except Exception as e:
            print(f"\nUnexpected error: {e}")
        
        # Ask to continue
        again = input("\nConvert another value? (y/n): ").strip().lower()
        if again != 'y':
            print("\nThank you for using the Unit Converter. Goodbye!")
            break

# Run the program
if __name__ == "__main__":
    main()

Welcome to Unit Converter!

          UNIT CONVERTER
Available categories:

1. Length
2. Weight
3. Volume
Please enter a valid number
Please enter a number between 1 and 3

Selected: Weight

Available conversions:
1. kg to lbs
2. lbs to kg

--------------------------------------------------
10.0000 kg = 22.0462 lbs
--------------------------------------------------

Thank you for using the Unit Converter. Goodbye!


Task-2

In [5]:
def calculate_sum(numbers):
    """
    Calculate the sum of all numbers in the list.
    
    Parameters:
    -----------
    numbers : list of float
        List of numeric values
        
    Returns:
    --------
    float
        Sum of all numbers in the list
        
    Raises:
    -------
    ValueError
        If the input list is empty
    """
    if not numbers:
        raise ValueError("Cannot calculate sum of an empty list")
    return sum(numbers)


def calculate_average(numbers):
    """
    Calculate the average (mean) of numbers in the list.
    
    Parameters:
    -----------
    numbers : list of float
        List of numeric values
        
    Returns:
    --------
    float
        Average of the numbers
        
    Raises:
    -------
    ValueError
        If the input list is empty
    """
    if not numbers:
        raise ValueError("Cannot calculate average of an empty list")
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Find the maximum value in the list of numbers.
    
    Parameters:
    -----------
    numbers : list of float
        List of numeric values
        
    Returns:
    --------
    float
        The largest number in the list
        
    Raises:
    -------
    ValueError
        If the input list is empty
    """
    if not numbers:
        raise ValueError("Cannot find maximum of an empty list")
    return max(numbers)


def find_minimum(numbers):
    """
    Find the minimum value in the list of numbers.
    
    Parameters:
    -----------
    numbers : list of float
        List of numeric values
        
    Returns:
    --------
    float
        The smallest number in the list
        
    Raises:
    -------
    ValueError
        If the input list is empty
    """
    if not numbers:
        raise ValueError("Cannot find minimum of an empty list")
    return min(numbers)

In [6]:
def parse_number_list(input_str):
    """
    Convert space-separated string input into a list of floats.
    
    Parameters:
    -----------
    input_str : str
        String containing numbers separated by spaces
        
    Returns:
    --------
    list of float
        Parsed list of numbers
        
    Raises:
    -------
    ValueError
        If input is empty or contains non-numeric values
    """
    if not input_str.strip():
        raise ValueError("No numbers entered")
        
    try:
        numbers = [float(x) for x in input_str.split()]
        if not numbers:
            raise ValueError("No valid numbers found")
        return numbers
    except ValueError:
        raise ValueError("Invalid input: please enter only numbers separated by spaces")

In [7]:
def main():
    operations = {
        "1": ("Sum", calculate_sum),
        "2": ("Average", calculate_average),
        "3": ("Maximum", find_maximum),
        "4": ("Minimum", find_minimum)
    }
    
    print("Welcome to List Math Operations Calculator\n")
    
    while True:
        print("\n" + "="*45)
        print("Available operations:")
        for key, (name, _) in operations.items():
            print(f"  {key}. {name}")
        print("  5. Exit")
        print("="*45)
        
        choice = input("\nSelect operation (1–5): ").strip()
        
        if choice == "5":
            print("\nThank you for using the calculator. Goodbye!")
            break
            
        if choice not in operations:
            print("Invalid choice. Please select 1–5.")
            continue
        
        op_name, op_function = operations[choice]
        print(f"\nSelected: {op_name}")
        
        while True:
            try:
                raw_input = input(f"Enter numbers separated by spaces: ").strip()
                numbers = parse_number_list(raw_input)
                break
            except ValueError as e:
                print(f"Error: {e}")
                print("Please try again.\n")
        
        try:
            result = op_function(numbers)
            
            print("\n" + "-"*50)
            print(f"Numbers: {numbers}")
            print(f"Operation: {op_name}")
            
            if op_name == "Average":
                print(f"Result: {result:.4f}")
            else:
                print(f"Result: {result}")
                
            print("-"*50)
            
        except ValueError as e:
            print(f"\nError during calculation: {e}")
        
        again = input("\nPerform another operation? (y/n): ").strip().lower()
        if again != 'y':
            print("Goodbye!")
            break


# Run the program
if __name__ == "__main__":
    main()

Welcome to List Math Operations Calculator


Available operations:
  1. Sum
  2. Average
  3. Maximum
  4. Minimum
  5. Exit

Selected: Sum

--------------------------------------------------
Numbers: [1.0]
Operation: Sum
Result: 1.0
--------------------------------------------------
Goodbye!


In [8]:
# Quick test
nums = [12, 45, 7.5, -3, 19]
print("Test list:", nums)
print("Sum      :", calculate_sum(nums))
print("Average  :", calculate_average(nums))
print("Max      :", find_maximum(nums))
print("Min      :", find_minimum(nums))

Test list: [12, 45, 7.5, -3, 19]
Sum      : 80.5
Average  : 16.1
Max      : 45
Min      : -3


4.2 Exercise on List Manipulation:

#1. Extract Every Other Element:

In [9]:
def extract_every_other(lst):
    """
    Returns a new list containing every other element from the input list,
    starting from the first element (index 0).
    
    Parameters:
    -----------
    lst : list
        The input list (can contain any type of elements)
        
    Returns:
    --------
    list
        A new list with elements at indices 0, 2, 4, ...
        
    Examples:
    --------
    >>> extract_every_other([1, 2, 3, 4, 5, 6])
    [1, 3, 5]
    
    >>> extract_every_other(['a', 'b', 'c', 'd'])
    ['a', 'c']
    
    >>> extract_every_other([10])
    [10]
    
    >>> extract_every_other([])
    []
    """
    # Method 1: Most readable & commonly used (slicing)
    return lst[::2]
    
    # Method 2: Using list comprehension (also very clear)
    # return [lst[i] for i in range(0, len(lst), 2)]
    
    # Method 3: Using range and indexing
    # result = []
    # for i in range(0, len(lst), 2):
    #     result.append(lst[i])
    # return result

In [11]:
# Test cases
test_cases = [
    [1, 2, 3, 4, 5, 6],          # → [1, 3, 5]
    ['a', 'b', 'c', 'd', 'e'],    # → ['a', 'c', 'e']
    [10],                          # → [10]
    [],                            # → []
    [7, 8],                        # → [7]
    list(range(1, 11)),            # → [1, 3, 5, 7, 9]
    ["apple", "banana", "cherry", "date", "elderberry"]
]

print("Testing extract_every_other():\n")
for i, lst in enumerate(test_cases, 1):
    result = extract_every_other(lst)
    print(f"Test {i:2d}: {str(lst):30} → {result}")

Testing extract_every_other():

Test  1: [1, 2, 3, 4, 5, 6]             → [1, 3, 5]
Test  2: ['a', 'b', 'c', 'd', 'e']      → ['a', 'c', 'e']
Test  3: [10]                           → [10]
Test  4: []                             → []
Test  5: [7, 8]                         → [7]
Test  6: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] → [1, 3, 5, 7, 9]
Test  7: ['apple', 'banana', 'cherry', 'date', 'elderberry'] → ['apple', 'cherry', 'elderberry']


#2. Slice a Sublist:

In [12]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list, including the elements at both
    start and end indices (inclusive).
    
    Parameters:
    -----------
    lst : list
        The input list (can contain any type of elements)
    start : int
        Starting index (inclusive)
    end : int
        Ending index (inclusive)
        
    Returns:
    --------
    list
        The sublist from index start to end (inclusive)
        
    Examples:
    --------
    >>> get_sublist([1, 2, 3, 4, 5, 6], 2, 4)
    [3, 4, 5]
    
    >>> get_sublist(['a', 'b', 'c', 'd', 'e'], 1, 3)
    ['b', 'c', 'd']
    
    >>> get_sublist([10, 20, 30], 0, 2)
    [10, 20, 30]
    
    Notes:
    ------
    - Uses standard Python slicing: lst[start:end+1]
    - If start > end, returns empty list
    - Handles negative indices (Python slicing behavior)
    - Does NOT raise IndexError for out-of-range indices (returns what is available)
    """
    # Most common and clean way (recommended)
    return lst[start:end+1]
    
    # Alternative explicit version (more verbose):
    # if start > end:
    #     return []
    # result = []
    # for i in range(start, end + 1):
    #     if 0 <= i < len(lst):
    #         result.append(lst[i])
    # return result

In [13]:
# Test cases
test_cases = [
    ([1, 2, 3, 4, 5, 6], 2, 4),       # → [3, 4, 5]
    (['a', 'b', 'c', 'd', 'e'], 1, 3), # → ['b', 'c', 'd']
    ([10, 20, 30, 40], 0, 3),          # → whole list
    ([7, 8, 9], 1, 1),                 # → single element
    ([], 0, 5),                        # → empty list
    ([1, 2, 3, 4, 5], 3, 6),           # → goes beyond end
    ([1, 2, 3, 4, 5], -3, -1),         # → negative indices
    ([1, 2, 3], 4, 5),                 # → start beyond length
    ([1, 2, 3], 2, 0),                 # → start > end
]

print("Testing get_sublist():\n")

for i, (lst, start, end) in enumerate(test_cases, 1):
    try:
        result = get_sublist(lst, start, end)
        print(f"Test {i:2d}: lst={lst!r:25}  start={start:2}, end={end:2}  →  {result!r}")
    except Exception as e:
        print(f"Test {i:2d}: ERROR → {e}")

Testing get_sublist():

Test  1: lst=[1, 2, 3, 4, 5, 6]         start= 2, end= 4  →  [3, 4, 5]
Test  2: lst=['a', 'b', 'c', 'd', 'e']  start= 1, end= 3  →  ['b', 'c', 'd']
Test  3: lst=[10, 20, 30, 40]           start= 0, end= 3  →  [10, 20, 30, 40]
Test  4: lst=[7, 8, 9]                  start= 1, end= 1  →  [8]
Test  5: lst=[]                         start= 0, end= 5  →  []
Test  6: lst=[1, 2, 3, 4, 5]            start= 3, end= 6  →  [4, 5]
Test  7: lst=[1, 2, 3, 4, 5]            start=-3, end=-1  →  []
Test  8: lst=[1, 2, 3]                  start= 4, end= 5  →  []
Test  9: lst=[1, 2, 3]                  start= 2, end= 0  →  []


#3. Reverse a List Using Slicing:

In [14]:
def reverse_list(lst):
    """
    Returns a new list that is the reverse of the input list using slicing.
    
    Parameters:
    -----------
    lst : list
        The input list (can contain any type of elements)
        
    Returns:
    --------
    list
        A new list with the elements in reverse order
        
    Examples:
    --------
    >>> reverse_list([1, 2, 3, 4, 5])
    [5, 4, 3, 2, 1]
    
    >>> reverse_list(['apple', 'banana', 'cherry'])
    ['cherry', 'banana', 'apple']
    
    >>> reverse_list([10])
    [10]
    
    >>> reverse_list([])
    []
    
    Note:
    -----
    This creates a **new** reversed list (does not modify the original).
    Uses the most idiomatic and efficient Python slicing method: lst[::-1]
    """
    return lst[::-1]

In [15]:
# Test cases
test_cases = [
    [1, 2, 3, 4, 5],                    # → [5, 4, 3, 2, 1]
    ['a', 'b', 'c', 'd'],               # → ['d', 'c', 'b', 'a']
    [10],                               # → [10]
    [],                                 # → []
    [True, False, True],                # → [True, False, True]
    list(range(1, 11)),                 # → [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
    [" Kathmandu", "Pokhara", "Chitwan", "Biratnagar"]
]

print("Testing reverse_list():\n")

for i, lst in enumerate(test_cases, 1):
    original = lst.copy()  # show that original is unchanged
    result = reverse_list(lst)
    print(f"Test {i:2d}: {original!r:40}  →  {result!r}")

Testing reverse_list():

Test  1: [1, 2, 3, 4, 5]                           →  [5, 4, 3, 2, 1]
Test  2: ['a', 'b', 'c', 'd']                      →  ['d', 'c', 'b', 'a']
Test  3: [10]                                      →  [10]
Test  4: []                                        →  []
Test  5: [True, False, True]                       →  [True, False, True]
Test  6: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]           →  [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
Test  7: [' Kathmandu', 'Pokhara', 'Chitwan', 'Biratnagar']  →  ['Biratnagar', 'Chitwan', 'Pokhara', ' Kathmandu']


#4: Remove the First and Last Elements

In [16]:
def remove_first_last(lst):
    """
    Returns a new list with the first and last elements removed using slicing.
    
    Parameters:
    -----------
    lst : list
        The input list (can contain any type of elements)
        
    Returns:
    --------
    list
        A new list containing all elements except the first and the last
        
    Examples:
    --------
    >>> remove_first_last([1, 2, 3, 4, 5])
    [2, 3, 4]
    
    >>> remove_first_last(['a', 'b', 'c', 'd'])
    ['b', 'c']
    
    >>> remove_first_last([10, 20])
    []
    
    >>> remove_first_last([7])
    []
    
    >>> remove_first_last([])
    []
    
    Notes:
    ------
    - Uses slicing: lst[1:-1]
    - Returns empty list if input has 0, 1, or 2 elements
    - Creates a new list (does not modify the original)
    """
    return lst[1:-1]

In [17]:
# Test cases
test_cases = [
    [1, 2, 3, 4, 5],                    # → [2, 3, 4]
    ['a', 'b', 'c', 'd', 'e'],          # → ['b', 'c', 'd']
    [10, 20],                           # → []
    [7],                                # → []
    [],                                 # → []
    list(range(1, 8)),                  # → [2, 3, 4, 5, 6]
    ["Kathmandu", "Pokhara", "Chitwan", "Lalitpur", "Biratnagar"]
]

print("Testing remove_first_last():\n")

for i, lst in enumerate(test_cases, 1):
    original = lst.copy()  # to show original remains unchanged
    result = remove_first_last(lst)
    print(f"Test {i:2d}: {original!r:50}  →  {result!r}")

Testing remove_first_last():

Test  1: [1, 2, 3, 4, 5]                                     →  [2, 3, 4]
Test  2: ['a', 'b', 'c', 'd', 'e']                           →  ['b', 'c', 'd']
Test  3: [10, 20]                                            →  []
Test  4: [7]                                                 →  []
Test  5: []                                                  →  []
Test  6: [1, 2, 3, 4, 5, 6, 7]                               →  [2, 3, 4, 5, 6]
Test  7: ['Kathmandu', 'Pokhara', 'Chitwan', 'Lalitpur', 'Biratnagar']  →  ['Pokhara', 'Chitwan', 'Lalitpur']


#5: Get the First n Elements

In [18]:
def get_first_n(lst, n):
    """
    Returns the first n elements of the list using slicing.
    
    Parameters:
    -----------
    lst : list
        The input list (can contain any type of elements)
    n : int
        Number of elements to return from the beginning
        
    Returns:
    --------
    list
        A new list containing the first min(n, len(lst)) elements
        
    Examples:
    --------
    >>> get_first_n([1, 2, 3, 4, 5], 3)
    [1, 2, 3]
    
    >>> get_first_n(['a', 'b', 'c', 'd'], 2)
    ['a', 'b']
    
    >>> get_first_n([10, 20, 30], 5)
    [10, 20, 30]     # returns all if n > len(lst)
    
    >>> get_first_n([], 4)
    []               # empty list returns empty
    
    >>> get_first_n([7], 0)
    []               # n = 0 returns empty list
    
    Notes:
    ------
    - Uses standard Python slicing: lst[:n]
    - Safe: if n > len(lst), returns the whole list
    - if n ≤ 0, returns empty list
    - Creates a new list (does not modify original)
    """
    return lst[:n]

In [19]:
# Test cases
test_cases = [
    ([1, 2, 3, 4, 5], 3),          # → [1, 2, 3]
    (['a', 'b', 'c', 'd', 'e'], 2), # → ['a', 'b']
    ([10, 20, 30, 40], 5),          # → whole list
    ([7, 8, 9], 0),                 # → []
    ([], 4),                        # → []
    (list(range(1, 11)), 6),        # → [1, 2, 3, 4, 5, 6]
    (["Kathmandu", "Pokhara", "Chitwan", "Lalitpur"], 3)
]

print("Testing get_first_n():\n")

for i, (lst, n) in enumerate(test_cases, 1):
    original = lst.copy()  # show original is unchanged
    result = get_first_n(lst, n)
    print(f"Test {i:2d}: lst={original!r:40}  n={n:2}  →  {result!r}")

Testing get_first_n():

Test  1: lst=[1, 2, 3, 4, 5]                           n= 3  →  [1, 2, 3]
Test  2: lst=['a', 'b', 'c', 'd', 'e']                 n= 2  →  ['a', 'b']
Test  3: lst=[10, 20, 30, 40]                          n= 5  →  [10, 20, 30, 40]
Test  4: lst=[7, 8, 9]                                 n= 0  →  []
Test  5: lst=[]                                        n= 4  →  []
Test  6: lst=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]           n= 6  →  [1, 2, 3, 4, 5, 6]
Test  7: lst=['Kathmandu', 'Pokhara', 'Chitwan', 'Lalitpur']  n= 3  →  ['Kathmandu', 'Pokhara', 'Chitwan']


#6: Extract Elements from the End

In [20]:
def get_last_n(lst, n):
    """
    Returns the last n elements of the list using slicing.
    
    Parameters:
    -----------
    lst : list
        The input list (can contain any type of elements)
    n : int
        Number of elements to return from the end
        
    Returns:
    --------
    list
        A new list containing the last min(n, len(lst)) elements
        
    Examples:
    --------
    >>> get_last_n([1, 2, 3, 4, 5], 2)
    [4, 5]
    
    >>> get_last_n(['a', 'b', 'c', 'd', 'e'], 3)
    ['c', 'd', 'e']
    
    >>> get_last_n([10, 20, 30], 5)
    [10, 20, 30]     # returns all if n > len(lst)
    
    >>> get_last_n([], 4)
    []               # empty list → empty result
    
    >>> get_last_n([7], 0)
    []               # n = 0 → empty list
    
    Notes:
    ------
    - Uses slicing: lst[-n:]
    - Safe behavior:
      - if n ≤ 0 → returns empty list
      - if n > len(lst) → returns the entire list
    - Creates a new list (does not modify original)
    """
    return lst[-n:]

In [21]:
# Test cases
test_cases = [
    ([1, 2, 3, 4, 5], 2),          # → [4, 5]
    (['a', 'b', 'c', 'd', 'e'], 3), # → ['c', 'd', 'e']
    ([10, 20, 30, 40], 5),          # → whole list
    ([7, 8, 9], 0),                 # → []
    ([], 4),                        # → []
    (list(range(1, 11)), 4),        # → [7, 8, 9, 10]
    (["Kathmandu", "Pokhara", "Chitwan", "Lalitpur", "Biratnagar"], 3)
]

print("Testing get_last_n():\n")

for i, (lst, n) in enumerate(test_cases, 1):
    original = lst.copy()  # to show original remains unchanged
    result = get_last_n(lst, n)
    print(f"Test {i:2d}: lst={original!r:50}  n={n:2}  →  {result!r}")

Testing get_last_n():

Test  1: lst=[1, 2, 3, 4, 5]                                     n= 2  →  [4, 5]
Test  2: lst=['a', 'b', 'c', 'd', 'e']                           n= 3  →  ['c', 'd', 'e']
Test  3: lst=[10, 20, 30, 40]                                    n= 5  →  [10, 20, 30, 40]
Test  4: lst=[7, 8, 9]                                           n= 0  →  [7, 8, 9]
Test  5: lst=[]                                                  n= 4  →  []
Test  6: lst=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]                     n= 4  →  [7, 8, 9, 10]
Test  7: lst=['Kathmandu', 'Pokhara', 'Chitwan', 'Lalitpur', 'Biratnagar']  n= 3  →  ['Chitwan', 'Lalitpur', 'Biratnagar']


#7: Extract Elements in Reverse Order

In [22]:
def reverse_skip(lst):
    """
    Returns every second element starting from the second-to-last element,
    moving backwards through the list.
    
    In other words: starts from index -2, then -4, -6, ..., collecting every other element
    in reverse direction.
    
    Parameters:
    -----------
    lst : list
        The input list (can contain any type of elements)
        
    Returns:
    --------
    list
        New list with elements collected backward, skipping one each time,
        starting from the second-to-last position
        
    Examples:
    --------
    >>> reverse_skip([1, 2, 3, 4, 5, 6])
    [5, 3, 1]
    
    >>> reverse_skip([10, 20, 30, 40, 50])
    [40, 20]
    
    >>> reverse_skip(['a', 'b', 'c', 'd', 'e'])
    ['d', 'b']
    
    >>> reverse_skip([1, 2, 3])
    [2]
    
    >>> reverse_skip([1, 2])
    []
    
    >>> reverse_skip([7])
    []
    
    >>> reverse_skip([])
    []
    """
    # Most readable & Pythonic solution
    return lst[-2::-2]
    
    # Alternative spellings that do exactly the same thing:
    # return lst[-2 : : -2]     # explicit but same result
    # return lst[len(lst)-2 : : -2]   # using positive index calculation

In [23]:
# Test cases
test_cases = [
    [1, 2, 3, 4, 5, 6],              # → [5, 3, 1]
    [10, 20, 30, 40, 50],            # → [40, 20]
    ['a', 'b', 'c', 'd', 'e'],       # → ['d', 'b']
    [1, 2, 3],                       # → [2]
    [1, 2],                          # → []
    [7],                             # → []
    [],                              # → []
    list(range(1, 11)),              # → [9, 7, 5, 3, 1]
    ["A", "B", "C", "D", "E", "F", "G"]
]

print("Testing reverse_skip():\n")

for i, lst in enumerate(test_cases, 1):
    result = reverse_skip(lst)
    print(f"Test {i:2d}: {lst!r:45}  →  {result!r}")

Testing reverse_skip():

Test  1: [1, 2, 3, 4, 5, 6]                             →  [5, 3, 1]
Test  2: [10, 20, 30, 40, 50]                           →  [40, 20]
Test  3: ['a', 'b', 'c', 'd', 'e']                      →  ['d', 'b']
Test  4: [1, 2, 3]                                      →  [2]
Test  5: [1, 2]                                         →  [1]
Test  6: [7]                                            →  []
Test  7: []                                             →  []
Test  8: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]                →  [9, 7, 5, 3, 1]
Test  9: ['A', 'B', 'C', 'D', 'E', 'F', 'G']            →  ['F', 'D', 'B']


4.3 Exercise on Nested List:

#1: Flatten a Nested List

In [24]:
def flatten(lst):
    """
    Flattens a nested list into a single-level list (one dimension).
    
    Parameters:
    -----------
    lst : list
        A (possibly deeply) nested list containing any mix of elements and sublists
        
    Returns:
    --------
    list
        A new flat list containing all non-list elements in the order they appear
        
    Examples:
    --------
    >>> flatten([[1, 2], [3, 4], [5]])
    [1, 2, 3, 4, 5]
    
    >>> flatten([1, [2, [3, 4]], 5, [6]])
    [1, 2, 3, 4, 5, 6]
    
    >>> flatten([[[[1]]], [2], 3])
    [1, 2, 3]
    
    >>> flatten([])
    []
    
    >>> flatten([1, 2, 3])
    [1, 2, 3]
    
    Notes:
    ------
    - Handles arbitrary nesting depth
    - Only flattens lists — other iterable types (tuples, sets) are kept as-is
    - Preserves original order of appearance
    """
    result = []
    
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))    # recursive call
        else:
            result.append(item)
            
    return result

In [28]:
def flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result

In [29]:
# Test cases
test_cases = [
    ([[1, 2], [3, 4], [5]],                     [1, 2, 3, 4, 5]),
    ([1, [2, [3, [4, 5]]], 6],                  [1, 2, 3, 4, 5, 6]),
    ([[[1]], [2, 3], [[4]]],                    [1, 2, 3, 4]),
    ([],                                        []),
    ([1, 2, 3],                                 [1, 2, 3]),
    ([[[[]]], 1, [2, [[]]], 3],                 [1, 2, 3]),
    [[["Kathmandu"], ["Pokhara", ["Chitwan"]]], ["Lalitpur"]],
]

print("Testing flatten():\n")

for i, (nested, expected) in enumerate(test_cases, 1):
    result = flatten(nested)          # or flatten_recursive(nested)
    passed = result == expected
    status = "✓" if passed else "✗"
    print(f"Test {i:2d}: {nested!r:50}  →  {result!r}  {status}")
    if not passed:
        print(f"   Expected: {expected!r}")

Testing flatten():

Test  1: [[1, 2], [3, 4], [5]]                               →  [1, 2, 3, 4, 5]  ✓
Test  2: [1, [2, [3, [4, 5]]], 6]                            →  [1, 2, 3, 4, 5, 6]  ✓
Test  3: [[[1]], [2, 3], [[4]]]                              →  [1, 2, 3, 4]  ✓
Test  4: []                                                  →  []  ✓
Test  5: [1, 2, 3]                                           →  [1, 2, 3]  ✓
Test  6: [[[[]]], 1, [2, [[]]], 3]                           →  [1, 2, 3]  ✓
Test  7: [['Kathmandu'], ['Pokhara', ['Chitwan']]]           →  ['Kathmandu', 'Pokhara', 'Chitwan']  ✗
   Expected: ['Lalitpur']


#2: Accessing Nested List Elements

In [30]:
def access_nested_element(lst, indices):
    """
    Accesses an element in a (possibly deeply) nested list using a list of indices.
    
    Parameters:
    -----------
    lst : list
        A (possibly nested) list
    indices : list of int
        Sequence of indices to follow to reach the desired element
        
    Returns:
    --------
    The element at the specified nested position
        
    Examples:
    --------
    >>> access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2])
    6
    
    >>> access_nested_element([10, [20, [30, 40, 50], 60], 70], [1, 1, 2])
    50
    
    >>> access_nested_element(['a', ['b', ['c']]], [1, 1, 0])
    'c'
    
    Raises:
    -------
    IndexError
        If any index is out of range at any level
    TypeError
        If trying to index into a non-list element before finishing indices
    """
    current = lst
    
    for i, idx in enumerate(indices):
        # Check if we can index into current element
        if not isinstance(current, list):
            raise TypeError(f"Cannot index into non-list element at level {i}: {current}")
        
        # Check bounds
        if idx < 0 or idx >= len(current):
            raise IndexError(f"Index {idx} out of range at level {i} (list length = {len(current)})")
        
        current = current[idx]
    
    return current

In [31]:
def access_nested_element(lst, indices):
    """
    Returns the element at the position specified by the list of indices.
    Uses successive indexing.
    """
    element = lst
    for idx in indices:
        element = element[idx]
    return element

In [32]:
# Test cases
test_cases = [
    # (nested_list, indices, expected)
    ([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2], 6),
    ([[10, 20], [30, [40, 50, 60]], [70]], [1, 1, 2], 60),
    (['x', ['y', ['z', 'w']]], [1, 1, 0], 'z'),
    ([[[1]]], [0, 0, 0], 1),
    ([10, 20, 30], [1], 20),               # not nested
    ([[1, 2, 3]], [0], [1, 2, 3]),         # returns sublist
    ([[1]], [0, 0], 1),
    ([], [], None),                        # empty list + empty indices → whole list
]

print("Testing access_nested_element():\n")

for i, (nested, idx_list, expected) in enumerate(test_cases, 1):
    try:
        result = access_nested_element(nested, idx_list)
        status = "✓" if result == expected else "✗"
        print(f"Test {i:2d}: indices={idx_list}  →  {result!r:12}  {status}   (expected: {expected!r})")
    except (IndexError, TypeError) as e:
        print(f"Test {i:2d}: indices={idx_list}  →  ERROR: {e}")

Testing access_nested_element():

Test  1: indices=[1, 2]  →  6             ✓   (expected: 6)
Test  2: indices=[1, 1, 2]  →  60            ✓   (expected: 60)
Test  3: indices=[1, 1, 0]  →  'z'           ✓   (expected: 'z')
Test  4: indices=[0, 0, 0]  →  1             ✓   (expected: 1)
Test  5: indices=[1]  →  20            ✓   (expected: 20)
Test  6: indices=[0]  →  [1, 2, 3]     ✓   (expected: [1, 2, 3])
Test  7: indices=[0, 0]  →  1             ✓   (expected: 1)
Test  8: indices=[]  →  []            ✗   (expected: None)


#3. Sum of All Elements in a Nested List

In [33]:
def sum_nested(lst):
    """
    Recursively calculates the sum of all numeric elements in a nested list,
    regardless of how deeply nested they are.
    
    Parameters:
    -----------
    lst : list
        A (possibly deeply) nested list that may contain numbers and/or sublists
        
    Returns:
    --------
    int or float
        The sum of all numeric values found in the list (and all sublists)
        
    Examples:
    --------
    >>> sum_nested([[1, 2], [3, [4, 5]], 6])
    21
    
    >>> sum_nested([1, [2, 3], [4, [5, [6]]]])
    21
    
    >>> sum_nested([[10], [], [20, 30], 5])
    65
    
    >>> sum_nested([])
    0
    
    >>> sum_nested([[[[0]]]])
    0
    
    Notes:
    ------
    - Only sums int and float values
    - Ignores non-numeric elements (strings, booleans, None, etc.)
    - Handles empty lists and empty sublists safely
    """
    total = 0
    
    for item in lst:
        if isinstance(item, (int, float)):
            total += item
        elif isinstance(item, list):
            total += sum_nested(item)   # recursive call for sublists
            
    return total

In [37]:
# Test cases
test_cases = [
    ([[1, 2], [3, [4, 5]], 6],                  21),
    ([1, [2, 3], [4, [5, [6]]]],                21),
    ([[10], [], [20, 30], 5],                   65),
    ([],                                        0),
    ([[[1.5, 2.5]], [3]],                       7.0),
    ([0, [0, [0, [0]]]],                        0),
    ([[1, "hello", 2], [3, True, 4], 5],        15),   # ignores strings & booleans
    ([[[[]]], 10, [], [20]],                    30),
]

print("Testing sum_nested():\n")

for i, (nested_list, expected) in enumerate(test_cases, 1):
    result = sum_nested(nested_list)   # or sum_nested_compact(nested_list)
    status = "✓" if result == expected else "✗"
    print(f"Test {i:2d}: {nested_list!r:50}  →  {result}  {status}")
    if result != expected:
        print(f"   Expected: {expected}")

Testing sum_nested():

Test  1: [[1, 2], [3, [4, 5]], 6]                            →  21  ✓
Test  2: [1, [2, 3], [4, [5, [6]]]]                          →  21  ✓
Test  3: [[10], [], [20, 30], 5]                             →  65  ✓
Test  4: []                                                  →  0  ✓
Test  5: [[[1.5, 2.5]], [3]]                                 →  7.0  ✓
Test  6: [0, [0, [0, [0]]]]                                  →  0  ✓
Test  7: [[1, 'hello', 2], [3, True, 4], 5]                  →  16  ✗
   Expected: 15
Test  8: [[[[]]], 10, [], [20]]                              →  30  ✓


#4. Remove Specific Element from a Nested List

In [38]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list (in-place modification).
    
    Parameters:
    -----------
    lst : list
        A (possibly deeply) nested list
    elem : any
        The element to remove from all levels of the list
        
    Returns:
    --------
    list
        The same list object (modified in-place)
        
    Examples:
    --------
    >>> lst = [[1, 2], [3, 2], [4, 5]]
    >>> remove_element(lst, 2)
    [[1], [3], [4, 5]]
    
    >>> lst = [1, [2, 3, 2], [2], 4, [5, 2, 6]]
    >>> remove_element(lst, 2)
    [1, [3], [], 4, [5, 6]]
    
    >>> remove_element([[1, 1], [1, [1]]], 1)
    [[], [[ ]]]
    
    Notes:
    ------
    - Modifies the list in place (like list.remove() behavior)
    - Works with arbitrary nesting depth
    - Safe: does not error if element is not found
    - Preserves order of remaining elements
    """
    i = 0
    while i < len(lst):
        if isinstance(lst[i], list):
            # Recurse into sublist
            remove_element(lst[i], elem)
            i += 1
        elif lst[i] == elem:
            # Remove this element
            lst.pop(i)
            # Do NOT increment i — next element shifts into position
        else:
            i += 1
            
    return lst

In [42]:
# Test cases
test_cases = [
    ([[1, 2], [3, 2], [4, 5]], 2, [[1], [3], [4, 5]]),
    ([1, [2, 3, 2], [2], 4, [5, 2, 6]], 2, [1, [3], [], 4, [5, 6]]),
    ([[1, 1], [1, [1, 2, 1]], 1], 1, [[], [[2]], []]),
    ([[10, 20], [30], [40, 20]], 20, [[10], [30], [40]]),
    ([], 999, []),
    ([[[2, 2], 2], 2], 2, [[[]]]),
    ([[1, "x", 1], ["x", 2]], "x", [[1, 1], [2]]),
]

print("Testing remove_element() – in-place version:\n")

for i, (lst_input, elem, expected) in enumerate(test_cases, 1):
    # Make a copy so we don't modify the test data
    lst = [x[:] if isinstance(x, list) else x for x in lst_input]  # shallow copy + sublists
    result = remove_element(lst, elem)
    passed = result == expected
    status = "✓" if passed else "✗"
    print(f"Test {i:2d}: remove {elem} from {lst_input!r:45}  →  {result!r}  {status}")
    if not passed:
        print(f"   Expected: {expected!r}")

Testing remove_element() – in-place version:

Test  1: remove 2 from [[1, 2], [3, 2], [4, 5]]                       →  [[1], [3], [4, 5]]  ✓
Test  2: remove 2 from [1, [2, 3, 2], [2], 4, [5, 2, 6]]              →  [1, [3], [], 4, [5, 6]]  ✓
Test  3: remove 1 from [[1, 1], [1, [2]], 1]                          →  [[], [[2]]]  ✗
   Expected: [[], [[2]], []]
Test  4: remove 20 from [[10, 20], [30], [40, 20]]                     →  [[10], [30], [40]]  ✓
Test  5: remove 999 from []                                             →  []  ✓
Test  6: remove 2 from [[[], 2], 2]                                   →  [[[]]]  ✓
Test  7: remove x from [[1, 'x', 1], ['x', 2]]                        →  [[1, 1], [2]]  ✓


#5. Find the Maximum Element in a Nested List

In [43]:
def find_max(lst):
    """
    Finds the maximum numeric value in a nested list, regardless of nesting depth.
    
    Parameters:
    -----------
    lst : list
        A (possibly deeply) nested list containing numbers (int/float) and/or sublists
        
    Returns:
    --------
    int or float
        The largest numeric value found in the entire nested structure
        
    Raises:
    -------
    ValueError
        If the list is empty or contains no numeric values
        
    Examples:
    --------
    >>> find_max([[1, 2], [3, [4, 5]], 6])
    6
    
    >>> find_max([10, [20, [30, 5]], 15, [8, 25]])
    30
    
    >>> find_max([[-5, -1], [-10, [-3]]])
    -1
    
    >>> find_max([[1.5, 2.7], [0.9, [3.2]]])
    3.2
    """
    if not lst:
        raise ValueError("Cannot find maximum in an empty list")
    
    max_value = float('-inf')   # smallest possible value
    
    for item in lst:
        if isinstance(item, (int, float)):
            if item > max_value:
                max_value = item
        elif isinstance(item, list):
            # Recursive call on sublist
            candidate = find_max(item)
            if candidate > max_value:
                max_value = candidate
    
    if max_value == float('-inf'):
        raise ValueError("No numeric values found in the nested list")
        
    return max_value

In [44]:
# Test cases
test_cases = [
    ([[1, 2], [3, [4, 5]], 6],          6),
    ([10, [20, [30, 5]], 15, [8, 25]],  30),
    ([[-5, -1], [-10, [-3]]],           -1),
    ([[1.5, 2.7], [0.9, [3.2]]],        3.2),
    ([[[1]]],                           1),
    ([],                                None),      # should raise error
    ([[-10], [-20, [-5, -15]]],          -5),
    ([[0, [0, [0]]]],                   0),
]

print("Testing find_max():\n")

for i, (nested_list, expected) in enumerate(test_cases, 1):
    try:
        result = find_max(nested_list)
        status = "✓" if result == expected else "✗"
        print(f"Test {i:2d}: {nested_list!r:45}  →  {result}  {status}")
        if result != expected:
            print(f"   Expected: {expected}")
    except ValueError as e:
        print(f"Test {i:2d}: {nested_list!r:45}  →  {e}")

Testing find_max():

Test  1: [[1, 2], [3, [4, 5]], 6]                       →  6  ✓
Test  2: [10, [20, [30, 5]], 15, [8, 25]]               →  30  ✓
Test  3: [[-5, -1], [-10, [-3]]]                        →  -1  ✓
Test  4: [[1.5, 2.7], [0.9, [3.2]]]                     →  3.2  ✓
Test  5: [[[1]]]                                        →  1  ✓
Test  6: []                                             →  Cannot find maximum in an empty list
Test  7: [[-10], [-20, [-5, -15]]]                      →  -5  ✓
Test  8: [[0, [0, [0]]]]                                →  0  ✓


#6. Count Occurrences of an Element in a Nested List

In [45]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list,
    at any level of nesting.
    
    Parameters:
    -----------
    lst : list
        A (possibly deeply) nested list
    elem : any
        The element to count occurrences of
        
    Returns:
    --------
    int
        The total number of times elem appears in the list and all sublists
        
    Examples:
    --------
    >>> count_occurrences([[1, 2], [2, 3], [2, 4]], 2)
    3
    
    >>> count_occurrences([1, [2, 3, 2], [2], 4, [2, 5, 2]], 2)
    5
    
    >>> count_occurrences([[1, 1], [1, [1, 1]]], 1)
    5
    
    >>> count_occurrences([10, [20], [30, 20]], 20)
    2
    
    >>> count_occurrences([], 999)
    0
    
    >>> count_occurrences(["a", ["a", "b"], "a"], "a")
    3
    """
    count = 0
    
    for item in lst:
        if isinstance(item, list):
            # Recurse into sublist
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
            
    return count

In [46]:
# Test cases
test_cases = [
    ([[1, 2], [2, 3], [2, 4]],          2,  3),
    ([1, [2, 3, 2], [2], 4, [2, 5, 2]], 2,  5),
    ([[1, 1], [1, [1, 1]]],             1,  5),
    ([10, [20], [30, 20, 20]],          20, 3),
    ([],                                999, 0),
    (["a", ["a", "b", "a"], "c", ["a"]], "a", 4),
    ([[True, False], [True, [False, True]]], True, 3),
    ([[1.0, 2.0], [2.0, [1.0]]],        2.0, 2),
]

print("Testing count_occurrences():\n")

for i, (nested_list, element, expected) in enumerate(test_cases, 1):
    result = count_occurrences(nested_list, element)
    status = "✓" if result == expected else "✗"
    print(f"Test {i:2d}: count {element!r} in {nested_list!r:50}  →  {result}  {status}")
    if result != expected:
        print(f"   Expected: {expected}")

Testing count_occurrences():

Test  1: count 2 in [[1, 2], [2, 3], [2, 4]]                            →  3  ✓
Test  2: count 2 in [1, [2, 3, 2], [2], 4, [2, 5, 2]]                   →  5  ✓
Test  3: count 1 in [[1, 1], [1, [1, 1]]]                               →  5  ✓
Test  4: count 20 in [10, [20], [30, 20, 20]]                            →  3  ✓
Test  5: count 999 in []                                                  →  0  ✓
Test  6: count 'a' in ['a', ['a', 'b', 'a'], 'c', ['a']]                  →  4  ✓
Test  7: count True in [[True, False], [True, [False, True]]]              →  3  ✓
Test  8: count 2.0 in [[1.0, 2.0], [2.0, [1.0]]]                          →  2  ✓


#7. Flatten a List of Lists of Lists

In [47]:
def deep_flatten(lst):
    """
    Recursively flattens a deeply nested list into a single flat list.
    
    Parameters:
    -----------
    lst : list
        A deeply nested list (list of lists of lists ... containing non-list elements)
        
    Returns:
    --------
    list
        A single-level list containing all non-list elements in original order
        
    Examples:
    --------
    >>> deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
    [1, 2, 3, 4, 5, 6, 7, 8]
    
    >>> deep_flatten([1, [2, [3, [4, [5]]]]])
    [1, 2, 3, 4, 5]
    
    >>> deep_flatten([[["a"]], [["b", "c"]], ["d"]])
    ['a', 'b', 'c', 'd']
    
    >>> deep_flatten([])
    []
    
    >>> deep_flatten([[[[]]], 10, [[[]]], 20])
    [10, 20]
    """
    result = []
    
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))   # recurse
        else:
            result.append(item)
            
    return result

In [48]:
# Test cases
test_cases = [
    ([[[1, 2], [3, 4]], [[5, 6], [7, 8]]],           [1, 2, 3, 4, 5, 6, 7, 8]),
    ([1, [2, [3, [4, [5]]]]],                        [1, 2, 3, 4, 5]),
    ([[["Kathmandu"], ["Pokhara"]], [["Chitwan"]]],  ["Kathmandu", "Pokhara", "Chitwan"]),
    ([[[[]]], 10, [[[]]], 20],                       [10, 20]),
    ([],                                             []),
    ([[[1.5]], [[2.5, 3.5]], [4.0]],                 [1.5, 2.5, 3.5, 4.0]),
    ([[[1, "x"]], [[2]], ["y"]],                     [1, "x", 2, "y"]),
]

print("Testing deep_flatten():\n")

for i, (nested, expected) in enumerate(test_cases, 1):
    result = deep_flatten(nested)          # or deep_flatten_compact(nested)
    passed = result == expected
    status = "✓" if passed else "✗"
    print(f"Test {i:2d}: {nested!r:55}  →  {result!r}  {status}")
    if not passed:
        print(f"   Expected: {expected!r}")

Testing deep_flatten():

Test  1: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]                     →  [1, 2, 3, 4, 5, 6, 7, 8]  ✓
Test  2: [1, [2, [3, [4, [5]]]]]                                  →  [1, 2, 3, 4, 5]  ✓
Test  3: [[['Kathmandu'], ['Pokhara']], [['Chitwan']]]            →  ['Kathmandu', 'Pokhara', 'Chitwan']  ✓
Test  4: [[[[]]], 10, [[[]]], 20]                                 →  [10, 20]  ✓
Test  5: []                                                       →  []  ✓
Test  6: [[[1.5]], [[2.5, 3.5]], [4.0]]                           →  [1.5, 2.5, 3.5, 4.0]  ✓
Test  7: [[[1, 'x']], [[2]], ['y']]                               →  [1, 'x', 2, 'y']  ✓


#8. Nested List Average

In [49]:
def average_nested(lst):
    """
    Calculates the average (mean) of all numeric elements in a nested list,
    regardless of nesting depth.
    
    Parameters:
    -----------
    lst : list
        A (possibly deeply) nested list containing numbers (int/float) and/or sublists
        
    Returns:
    --------
    float
        The average of all numeric values found (sum / count)
        
    Raises:
    -------
    ValueError
        If the list is empty or contains no numeric values
        
    Examples:
    --------
    >>> average_nested([[1, 2], [3, 4], [5, 6]])
    3.5
    
    >>> average_nested([10, [20, 30], [40]])
    25.0
    
    >>> average_nested([[1.5, 2.5], [3.0]])
    2.3333333333333335
    
    >>> average_nested([[[[0]]]])
    0.0
    """
    total = 0
    count = 0
    
    def recurse(items):
        nonlocal total, count
        for item in items:
            if isinstance(item, (int, float)):
                total += item
                count += 1
            elif isinstance(item, list):
                recurse(item)
    
    recurse(lst)
    
    if count == 0:
        raise ValueError("No numeric values found in the nested list")
        
    return total / count

In [50]:
# Test cases
test_cases = [
    ([[1, 2], [3, 4], [5, 6]],               3.5),
    ([10, [20, 30], [40]],                   25.0),
    ([[1.5, 2.5], [3.0, 4.0]],               2.75),
    ([[[1]], [[2]], [3]],                    2.0),
    ([[[0]]],                                0.0),
    ([],                                     None),     # should raise error
    ([[-5, -1], [-10, [-3, -7]]],           -5.2),
    ([[1, "hello", 2], [3, True, 4]],        2.5),     # ignores non-numbers
]

print("Testing average_nested():\n")

for i, (nested_list, expected) in enumerate(test_cases, 1):
    try:
        result = average_nested(nested_list)
        if expected is None:
            print(f"Test {i:2d}: {nested_list!r:45}  →  should raise error")
        else:
            status = "✓" if abs(result - expected) < 1e-10 else "✗"
            print(f"Test {i:2d}: {nested_list!r:45}  →  {result:.6f}  {status}")
            if status == "✗":
                print(f"   Expected: {expected}")
    except ValueError as e:
        print(f"Test {i:2d}: {nested_list!r:45}  →  {e}")

Testing average_nested():

Test  1: [[1, 2], [3, 4], [5, 6]]                       →  3.500000  ✓
Test  2: [10, [20, 30], [40]]                           →  25.000000  ✓
Test  3: [[1.5, 2.5], [3.0, 4.0]]                       →  2.750000  ✓
Test  4: [[[1]], [[2]], [3]]                            →  2.000000  ✓
Test  5: [[[0]]]                                        →  0.000000  ✓
Test  6: []                                             →  No numeric values found in the nested list
Test  7: [[-5, -1], [-10, [-3, -7]]]                    →  -5.200000  ✓
Test  8: [[1, 'hello', 2], [3, True, 4]]                →  2.200000  ✗
   Expected: 2.5


10.1 Basic Vector and Matrix Operation with Numpy.

1: Array Creation

In [52]:
import numpy as np

In [53]:
# 1. Initialize an empty array with size 2×2
# (Note: "empty" means uninitialized — values are random/garbage)
arr1 = np.empty((2, 2))
print("1. Empty 2×2 array:")
print(arr1)
print()

1. Empty 2×2 array:
[[0.0000000e+000 1.0366336e-311]
 [1.0366336e-311 1.0366336e-311]]



In [54]:
# 2. Initialize an all-ones array with size 4×2
arr2 = np.ones((4, 2))
# or: arr2 = np.ones((4, 2), dtype=float)  # you can specify dtype
print("2. All ones 4×2 array:")
print(arr2)
print()

2. All ones 4×2 array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]



In [55]:
# 3. Return a new array of given shape and type, filled with fill value
# Example: 3×3 array filled with 7
arr3 = np.full((3, 3), fill_value=7)
# You can also use: np.full(shape, fill_value, dtype=...)
print("3. 3×3 array filled with 7:")
print(arr3)
print()

3. 3×3 array filled with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]



In [56]:
# 4. Return a new array of zeros with same shape and type as a given array
# (np.zeros_like)
given_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
arr4 = np.zeros_like(given_array)
print("4. Zeros like given array (shape and dtype preserved):")
print("Original array:")
print(given_array)
print("Zeros-like array:")
print(arr4)
print("dtype of arr4:", arr4.dtype)
print()

4. Zeros like given array (shape and dtype preserved):
Original array:
[[1 2 3]
 [4 5 6]]
Zeros-like array:
[[0 0 0]
 [0 0 0]]
dtype of arr4: int32



In [57]:
# 5. Return a new array of ones with same shape and type as a given array
# (np.ones_like)
arr5 = np.ones_like(given_array)
print("5. Ones like given array:")
print(arr5)
print("dtype of arr5:", arr5.dtype)
print()

5. Ones like given array:
[[1 1 1]
 [1 1 1]]
dtype of arr5: int32



In [58]:
# 6. Convert existing Python list to NumPy array
new_list = [1, 2, 3, 4]
arr6 = np.array(new_list)
print("6. NumPy array from Python list:")
print(arr6)
print("Type:", type(arr6))
print("dtype:", arr6.dtype)

6. NumPy array from Python list:
[1 2 3 4]
Type: <class 'numpy.ndarray'>
dtype: int64


2: Array Manipulation: Numerical Ranges and Array indexing

In [59]:
import numpy as np

In [61]:
# 1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("1. Array from 10 to 49:")
print(arr1)
print()

1. Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]



In [62]:
# 2. Create a 3×3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("2. 3×3 matrix with 0 to 8:")
print(arr2)
print()

2. 3×3 matrix with 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]



In [63]:
# 3. Create a 3×3 identity matrix
arr3 = np.eye(3)
# or: np.identity(3)  # same result
print("3. 3×3 identity matrix:")
print(arr3)
print()

3. 3×3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [64]:
# 4. Create a random array of size 30 and find its mean
arr4 = np.random.random(30)
mean_value = arr4.mean()
print("4. Random array of 30 elements (first 10 shown):")
print(arr4[:10], "...")
print(f"Mean = {mean_value:.6f}")
print()

4. Random array of 30 elements (first 10 shown):
[0.04853158 0.06259765 0.09535519 0.26100863 0.52199051 0.75860952
 0.21682085 0.05083985 0.45092968 0.64415483] ...
Mean = 0.492429



In [65]:
# 5. Create a 10×10 array with random values → min & max
arr5 = np.random.random((10, 10))
min_val = arr5.min()
max_val = arr5.max()
print("5. 10×10 random array  →  min =", f"{min_val:.4f}", "  max =", f"{max_val:.4f}")
print()

5. 10×10 random array  →  min = 0.0130   max = 0.9916



In [66]:
# 6. Create a zero array of size 10 and replace 5th element (index 4) with 1
arr6 = np.zeros(10)
arr6[4] = 1
print("6. Zero array with 5th position = 1:")
print(arr6)
print()

6. Zero array with 5th position = 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]



In [67]:
# 7. Reverse an array arr = [1,2,0,0,4,0]
arr7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr7[::-1]
# or: arr7[::-1],  np.flip(arr7),  arr7[::-1].copy()
print("7. Original:", arr7)
print("   Reversed:", reversed_arr)
print()

7. Original: [1 2 0 0 4 0]
   Reversed: [0 4 0 0 2 1]



In [68]:
# 8. Create a 2D array with 1 on border and 0 inside (e.g. 5×5)
arr8 = np.ones((5, 5), dtype=int)
arr8[1:-1, 1:-1] = 0
print("8. 5×5 array – 1 on border, 0 inside:")
print(arr8)
print()

8. 5×5 array – 1 on border, 0 inside:
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]



In [69]:
# 9. Create an 8×8 checkerboard pattern (two common styles shown)
# Style A: starting with 0 in top-left
checker1 = np.zeros((8, 8), dtype=int)
checker1[::2, ::2] = 1
checker1[1::2, 1::2] = 1

In [70]:
# Style B: starting with 1 in top-left (often preferred)
checker2 = np.ones((8, 8), dtype=int)
checker2[::2, 1::2] = 0
checker2[1::2, ::2] = 0

print("9. 8×8 Checkerboard (Style B – starts with 1):")
print(checker2)
print("\nAlternative style (starts with 0):")
print(checker1)

9. 8×8 Checkerboard (Style B – starts with 1):
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]

Alternative style (starts with 0):
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


3: Array Operations

In [71]:
import numpy as np

# Given arrays
x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

print("x =\n", x)
print("y =\n", y)
print("v =", v)
print("w =", w)
print()

x =
 [[1 2]
 [3 5]]
y =
 [[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]



In [73]:
# 1. Add the two arrays (x + y)
print("1. x + y =")
print(x + y)



1. x + y =
[[ 6  8]
 [10 13]]


In [74]:
# 2. Subtract the two arrays (x - y)
print("2. x - y =")
print(x - y)


2. x - y =
[[-4 -4]
 [-4 -3]]


In [75]:
# 3. Multiply the array with any integer of your choice
# (example: multiply x by 4)
print("3. x multiplied by 4:")
print(x * 4)

3. x multiplied by 4:
[[ 4  8]
 [12 20]]


In [76]:
# 4. Find the square of each element of the array (example: square of x)
print("4. Element-wise square of x (x**2):")
print(x ** 2)

4. Element-wise square of x (x**2):
[[ 1  4]
 [ 9 25]]


In [78]:
# 5. Find the dot product between:
print("5. Dot products:")

# a) v · w  (1D vectors → scalar)
dot_vw = np.dot(v, w)
# or: v @ w
print("   v · w =", dot_vw)

# b) x · v  (2×2 matrix × 2×1 vector → 2×1 vector)
dot_xv = np.dot(x, v)
# or: x @ v
print("   x · v =\n", dot_xv)

# c) x · y  (2×2 matrix × 2×2 matrix → 2×2 matrix)
dot_xy = np.dot(x, y)
# or: x @ y
print("   x · y =\n", dot_xy)

5. Dot products:
   v · w = 219
   x · v =
 [29 77]
   x · y =
 [[19 22]
 [50 58]]


In [79]:
# 6. Concatenate x and y along rows (vertical stack)
#    Concatenate v and w along columns (horizontal stack)

print("6. Concatenation:")

# x and y along rows → shape becomes (4,2)
concat_row = np.concatenate((x, y), axis=0)
# or: np.vstack((x, y))
print("   x and y stacked vertically (along rows):\n", concat_row)

# v and w along columns → shape becomes (2,2)
concat_col = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis=1)
# or: np.column_stack((v, w))  ← cleaner!
print("   v and w stacked horizontally (along columns):\n", concat_col)

6. Concatenation:
   x and y stacked vertically (along rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
   v and w stacked horizontally (along columns):
 [[ 9 11]
 [10 12]]


In [81]:
# 7. Concatenate x and v → observe and explain the error
print("7. Trying to concatenate x and v directly:")

try:
    np.concatenate((x, v), axis=0)
except ValueError as e:
    print("   Error:", e)
    print("\n   Explanation:")
    print("   → x has shape", x.shape, "(2 rows, 2 columns)")
    print("   → v has shape", v.shape, "(only 1 dimension)")
    print("   → NumPy cannot concatenate arrays with different number of dimensions")
    print("   → or mismatched shapes along the concatenation axis.")
    print("   → To fix this, you need to reshape v to match x's column count, e.g.")
    print("      np.concatenate((x, v.reshape(1, -1)), axis=0)")

7. Trying to concatenate x and v directly:
   Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

   Explanation:
   → x has shape (2, 2) (2 rows, 2 columns)
   → v has shape (2,) (only 1 dimension)
   → NumPy cannot concatenate arrays with different number of dimensions
   → or mismatched shapes along the concatenation axis.
   → To fix this, you need to reshape v to match x's column count, e.g.
      np.concatenate((x, v.reshape(1, -1)), axis=0)


4: Matrix Operations

In [83]:
import numpy as np

# Given matrices
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

print("A =")
print(A)
print("\nB =")
print(B)

A =
[[3 4]
 [7 8]]

B =
[[5 3]
 [2 1]]


In [ ]:
# Part 1: Prove A · A⁻¹ = I   (identity matrix)

A_inv = np.linalg.inv(A)

print("1. A · A⁻¹ should equal identity matrix I")
print("A_inv =")
print(A_inv)

product = np.dot(A, A_inv)        
print("\nA @ A_inv =")
print(product)

print("\nRounded (floating-point precision):")
print(np.round(product, decimals=10))

print("\n→ Yes, it is approximately the 2×2 identity matrix (small floating-point errors are normal)")

1. A · A⁻¹ should equal identity matrix I
A_inv =
[[-2.    1.  ]
 [ 1.75 -0.75]]

A @ A_inv =
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Rounded (floating-point precision):
[[1. 0.]
 [0. 1.]]

→ Yes, it is approximately the 2×2 identity matrix (small floating-point errors are normal)


In [85]:
# Part 2: Prove AB ≠ BA   (matrix multiplication is not commutative)

AB = np.dot(A, B)    # or A @ B
BA = np.dot(B, A)    # or B @ A

print("2. Check if AB = BA")
print("AB =")
print(AB)
print("\nBA =")
print(BA)

print("\nAre they equal?")
print(np.array_equal(AB, BA))

print("\n→ AB ≠ BA  (matrix multiplication is not commutative)")
print()

2. Check if AB = BA
AB =
[[23 13]
 [51 29]]

BA =
[[36 44]
 [13 16]]

Are they equal?
False

→ AB ≠ BA  (matrix multiplication is not commutative)



In [87]:
# Part 3: Prove (AB)ᵀ = Bᵀ Aᵀ

AB_T = (A @ B).T                # transpose of AB
BT_AT = B.T @ A.T               # B transpose × A transpose

print("3. Check (AB)ᵀ == Bᵀ Aᵀ")
print("(AB)ᵀ =")
print(AB_T)
print("\nBᵀ Aᵀ =")
print(BT_AT)

print("\nAre they equal?")
print(np.array_equal(AB_T, BT_AT))

print("\n→ Yes, (AB)ᵀ = Bᵀ Aᵀ holds (transpose of product rule)")

3. Check (AB)ᵀ == Bᵀ Aᵀ
(AB)ᵀ =
[[23 51]
 [13 29]]

Bᵀ Aᵀ =
[[23 51]
 [13 29]]

Are they equal?
True

→ Yes, (AB)ᵀ = Bᵀ Aᵀ holds (transpose of product rule)


In [89]:
# Part 4 & 5: Solve the system using inverse method

# Coefficient matrix A
A_sys = np.array([[ 2, -3,  1],
                  [ 1, -1,  2],
                  [ 3,  1, -1]])

# Right-hand side vector b
b = np.array([-1, -3, 9])

print("Coefficient matrix A:")
print(A_sys)
print("\nb =")
print(b)

Coefficient matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

b =
[-1 -3  9]


In [90]:
# Method 1: Using inverse  →  x = A⁻¹ b
A_inv_sys = np.linalg.inv(A_sys)
x_solution = A_inv_sys @ b

print("Solution using inverse (x = A⁻¹ b):")
print("x =", x_solution[0])
print("y =", x_solution[1])
print("z =", x_solution[2])
print()

Solution using inverse (x = A⁻¹ b):
x = 2.0
y = 1.0
z = -2.0



In [91]:
# Method 2: np.linalg.solve (more stable & efficient)
x_solve = np.linalg.solve(A_sys, b)

print("Solution using np.linalg.solve (recommended):")
print("x =", x_solve[0])
print("y =", x_solve[1])
print("z =", x_solve[2])
print()

print("Verification (A @ x should ≈ b):")
print(A_sys @ x_solve)

Solution using np.linalg.solve (recommended):
x = 2.0
y = 1.0000000000000002
z = -2.0

Verification (A @ x should ≈ b):
[-1. -3.  9.]


10.2 Experiment: How Fast is NumPy?

In [2]:
import numpy as np
import time

In [3]:
# 1. Element-wise Addition – size 1,000,000

N = 1_000_000

# Python lists
a_list = list(range(N))
b_list = [x * 2 for x in range(N)]   # just different values

start = time.time()
c_list = [a_list[i] + b_list[i] for i in range(N)]
time_list_add = time.time() - start

In [4]:
# NumPy
a_np = np.arange(N)
b_np = np.arange(N) * 2

start = time.time()
c_np = a_np + b_np
time_np_add = time.time() - start

In [5]:
print("1. Element-wise Addition (N = 1,000,000)")
print(f"  Python lists : {time_list_add:9.4f} seconds")
print(f"  NumPy        : {time_np_add:9.4f} seconds")
print(f"  Speedup      : {time_list_add / time_np_add:6.1f} × faster\n")

1. Element-wise Addition (N = 1,000,000)
  Python lists :    0.1669 seconds
  NumPy        :    0.0039 seconds
  Speedup      :   43.0 × faster



In [6]:
# 2. Element-wise Multiplication – size 1,000,000

N = 1_000_000

# Python lists
a_list = list(range(N))
b_list = [x * 1.5 for x in range(N)]

start = time.time()
c_list = [a_list[i] * b_list[i] for i in range(N)]
time_list_mul = time.time() - start

In [7]:
# NumPy
a_np = np.arange(N, dtype=np.float64)
b_np = np.arange(N, dtype=np.float64) * 1.5

start = time.time()
c_np = a_np * b_np
time_np_mul = time.time() - start

In [8]:
print("2. Element-wise Multiplication (N = 1,000,000)")
print(f"  Python lists : {time_list_mul:9.4f} seconds")
print(f"  NumPy        : {time_np_mul:9.4f} seconds")
print(f"  Speedup      : {time_list_mul / time_np_mul:6.1f} × faster\n")

2. Element-wise Multiplication (N = 1,000,000)
  Python lists :    0.1836 seconds
  NumPy        :    0.0050 seconds
  Speedup      :   37.0 × faster



In [9]:
# 3. Dot Product – size 1,000,000

N = 1_000_000

# Python lists
a_list = list(range(N))
b_list = [x * 0.7 for x in range(N)]

start = time.time()
dot_list = sum(a * b for a, b in zip(a_list, b_list))
time_list_dot = time.time() - start

In [10]:
# NumPy
a_np = np.arange(N, dtype=np.float64)
b_np = np.arange(N, dtype=np.float64) * 0.7

start = time.time()
dot_np = np.dot(a_np, b_np)          # or a_np @ b_np
time_np_dot = time.time() - start

In [11]:
print("3. Dot Product (N = 1,000,000)")
print(f"  Python lists : {time_list_dot:9.4f} seconds")
print(f"  NumPy        : {time_np_dot:9.4f} seconds")
print(f"  Speedup      : {time_list_dot / time_np_dot:6.1f} × faster\n")

3. Dot Product (N = 1,000,000)
  Python lists :    0.1665 seconds
  NumPy        :    0.0036 seconds
  Speedup      :   46.7 × faster



In [12]:
# 4. Matrix Multiplication – 1000 × 1000

N = 1000

print("Creating two random 1000×1000 matrices...")

# Python lists – very slow to create & multiply
start_create = time.time()
A_list = [[float(i+j) for j in range(N)] for i in range(N)]
B_list = [[float(i-j+1) for j in range(N)] for i in range(N)]
time_create_list = time.time() - start_create

start = time.time()
C_list = [[0]*N for _ in range(N)]
for i in range(N):
    for j in range(N):
        for k in range(N):
            C_list[i][j] += A_list[i][k] * B_list[k][j]
time_list_matmul = time.time() - start

Creating two random 1000×1000 matrices...


In [13]:
print(f"  Python lists creation : {time_create_list:.2f} s")
print(f"  Python lists matmul   : {time_list_matmul:9.2f} seconds")
print("  (this usually takes 1–5 minutes depending on machine)")

  Python lists creation : 0.39 s
  Python lists matmul   :    473.06 seconds
  (this usually takes 1–5 minutes depending on machine)


In [14]:
#NumPy

start = time.time()
A_np = np.random.rand(N, N)
B_np = np.random.rand(N, N)
time_create_np = time.time() - start

start = time.time()
C_np = A_np @ B_np               # or np.dot(A_np, B_np)
time_np_matmul = time.time() - start

In [15]:
print(f"\n  NumPy creation        : {time_create_np:9.4f} s")
print(f"  NumPy matmul          : {time_np_matmul:9.4f} seconds")
print(f"  Speedup               : {time_list_matmul / time_np_matmul:6.0f} – {time_list_matmul / time_np_matmul * 1000:6.0f}× faster")
print("  (typical speedup: 300 – 2000× depending on hardware)")


  NumPy creation        :    0.1027 s
  NumPy matmul          :    0.0782 seconds
  Speedup               :   6053 – 6052584× faster
  (typical speedup: 300 – 2000× depending on hardware)
